### ISSUE TITLE
seed part-1 dataset

### ISSUE THREAD

**Issue by Eureka-Maggie** [AILab-CVC/SEED-X#27]
Hi, I download all the source_images.tar.gz.part-* and cat them to source_images.tar.gz, which is 121G. But after I use 'tar -xzf' to unzip it , I only got 80,218 jpg files. There are no error messages.
I do the same thing to target_images.tar.gz and I got about 1.5M images.
Do you know what this is about? Does that make sense?
Really looking forward for your reply!

**Comment by liyuke65535** [comment]
Hi, could you please tell me where to download the source_images.tar.gz.part-* and target_images?

**Comment by Eureka-Maggie** [comment]
I downloaded them last year and it was in their hugging face repo at that time. I check the repo just now but I found no datasets...It seems they have moved or deleted the datasets.
